export const ASSOCATION_TABLE = {
    A: 'Thomas',
    B: 'Léa',
    C: 'Quentin',
    D: 'Kilian',
    E: 'Bernard',
    F: 'Hélène',
    G: 'Jean-Louis',
    H: 'Paul',
    I: 'Guillaume',
    J: 'Fanny',
    K: 'Olivier',
    L: 'Remy',
    M: 'Ulysse',
    N: 'Andréas',
    O: 'Marjolaine',
    P: 'Clément',
    Q: 'Victor',
    R: 'Xavier',
    S: 'Edward',
    T: 'Zoé',
    U: 'Nathan',
    V: 'Irène',
    W: 'Sébastien',
    X: 'Daniel',
    Y: 'Yves',
    Z: 'William'
}